# This is a basic workflow to help you get started with Actions
name: CI-CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  


#elasticbeanstalk-eu-north-1-807789500198
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install
          npm ci 
      # build and test the apps     
      - name: build
        run: |
          npm run build
          npm run test

  deploy_to_elastic_beanstalk:
    runs-on: ubuntu-latest
    needs: [build_test]

    steps: 

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1
      - name: Elastic Beanstalk Deployment
        # You may pin to the exact commit or the version.
        # uses: kumarshivam12/Aws-ElasticBeanstalk@3110dbc44126aba53f10be9d506f542d9e7d5d4f
        uses: kumarshivam12/Aws-ElasticBeanstalk@v1.4
        with:
          # Enter The Name of the S3 Bucket
          EB-BUCKET-NAME: elasticbeanstalk-eu-north-1-807789500198
          # Enter the name of the Elastic BeanStalk Application
          APPLICATION-NAME: docker
          # Name of the Elastic beanstalk Environment
          EB-ENV-NAME: docker-env
          # 
          DEPLOY-PACKAGE-NAME: # optional
          # Enter the Region
          AWS-REGION: eu-north-1